---

- file: 
    path: '{{ web_dir }}' 
    state: directory 
    owner: '{{ web_owner }}'
    group: '{{ web_group }}'
    mode: 0755

- file: 
    path: '/etc/nginx/sites-enabled/default'
    state: absent
