---

- file: 
    path: '{{ web_dir }}' 
    state: directory 
    owner: '{{ web_owner }}'
    group: '{{ web_group }}'
    mode: 0755

- name: remove default nginx configs
  file: dest=/etc/nginx/sites-available/default state=absent
