---
- name: Update apt-cache
  apt: update_cache=yes

- name: Install php-fpm and deps
  apt: name={{ item }} state=present
  with_items:
  - php7.0-common 
  - php7.0-json 
  - php7.0-opcache 
  - php7.0-readline 
  - php7.0-cli
  - php7.0-fpm
    #- name: Disable default pool
    #  command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled creates=/etc/php-fpm.d/www.disabled
    #  notify: restart php-fpm

    #- name: Copy php-fpm configuration
    #  template: src=wordpress.conf dest=/etc/php-fpm.d/
    #notify: restart php-fpm
